config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
#  get 'superadmins/index'
 # get 'superadmins/show'
 # get 'superadmins/new'

 # get 'superadmins/edit'
 # get 'admins/index'
#  get 'admins', to: 'admins#show'
 # get 'instructors/index'

 # get 'instructors/show'

 # get 'admins/index'

 # get 'admins', to: 'admins#show'

=======
>>>>>>> refs/remotes/origin/schen35

  #root to: 'users#index'
  root to: 'visitors#index'
  devise_for :users, :path =>'u'
  get '/superadmins/:id' => 'users#destroy'

  get 'index_instructor' => 'enrollments#index_instructor'
   get 'index_student' => 'enrollments#index_student'

  get '/enrollments', to: 'enrollments#new', as: 'student_enrollment'


  devise_scope :user do
<<<<<<< HEAD
    # get '/u/login', to: "devise/sessions#new", as: "login"
    # get '/u/logout', to: "devise/sessions#destroy", as: "logout"
    # get '/u/signout', to: "users/sessions#destroy", as: "signout"
    # get '/u/signup', to: "users#new", as: "signup"
=======
>>>>>>> refs/remotes/origin/schen35
    get '/u/sign_out' => 'devise/sessions#destroy'

  end


   resources :users
   resources :enrollments
   resources :courses
  resources :admins
  resources :superadmins
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user
  belongs_to :course

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]


  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  def index_instructor
    @user_id = current_user
    @enrollments = Enrollment.all
  end

  def index_student
    @user_id = current_user
    @enrollments = Enrollment.all
  end

  # GET /enrollments/new
  def new
    if can? :do_as_student, :all
    @courses= Course.all
    @users = User.all
    @course_id = session[:current_course]
    @course_find = @courses.where('"courses"."id" = ?', "#{@course_id}")
    @course_find.each do |course|
      @instructor_name = course.Instructor
      @user_find = @users.where('"users"."name" = ?', "#{@instructor_name}")
      @user_find.each do |user|
        @instructor_id = user.id
        session[:current_course_instructor_id]= @instructor_id
      end
    end
    @user_id = current_user
    @instructor_id = session[:current_course_instructor_id]
    end
    @enrollment = Enrollment.new
  end


  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)
    @course_id = params[:course_id_param]
    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    @enrollment = Enrollment.find(params[:id])
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:student_id, :instructor_id, :course_id, :grade, :material, :admission)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<div class="container row col-lg-12 col-md-12 col-sm-12" >
<%= form_for(@enrollment) do |f| %>

  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <fieldset>
    <% if can? :do_as_student, :all %>
    <% #@course_ID = params[:course_id] %>
        <% #@user_ID = params[:user_id] %>
        <div class="field">
          <%= f.label :student_id %><br>
          <%= f.number_field :student_id, :value => @user_id.id %>
        </div>
        <div class="field">
          <%= f.label :instructor_id %><br>
          <%= f.number_field :instructor_id, :value => @instructor_id %>

        </div>
        <div class="field">
          <%= f.label :course_id %><br>
          <%= f.number_field :course_id, :value => @course_id %>
        </div>
    <% else %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :instructor_id %><br>
    <%= f.number_field :instructor_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
 <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :material %><br>
    <%= f.text_area :material %>
  </div>
  <div class="field">
    <%= f.label :admission %><br>
    <%= f.check_box :admission %>
  </div>
<% end %>
        </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
    <div class="filed">
    </div>
<% end %>
</div>

app/views/enrollments/edit.html.erb
  <div class="container row col-md-4 col-md-offset-4" style="left: 0%; top: 70px;">
<h1>Editing Enrollment</h1>

<%= render 'form' %>


<%= link_to 'Show', @enrollment %>
    <% if can? :do_as_student, :all %>
 <%= link_to "Back", courses_path %>
    <% else %>
        <%= link_to 'Back', enrollments_path %>
    <% end %>
</div>

app/views/enrollments/index.html.erb
<div class="container row col-md-4 col-md-offset-4" style="left: 0%; top: 70px;">
<p id="notice"><%= notice %></p>

<h1>Listing Enrollments</h1>

<table>
  <thead>
    <tr>
      <th>Student id</th>
      <th>Instructor id</th>
      <th>Course id</th>
      <th>Grade</th>
      <th>Material</th>
      <th>Admission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.student_id %></td>
        <td><%= enrollment.instructor_id %></td>
        <td><%= enrollment.course_id %></td>
        <td><%= enrollment.grade %></td>
        <td><%= enrollment.material %></td>
        <td><%= enrollment.admission %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>
</div>

app/views/enrollments/index_instructor.html.erb
<div class="container row col-md-4 col-md-offset-4" style="left: 0%; top: 70px;">
  <p id="notice"><%= notice %></p>

  <h1>Listing Enrollments</h1>

  <table border="4">
    <thead>
    <tr>
      <th>Student id</th>
      <th>Instructor id</th>
      <th>Course id</th>
      <th>Grade</th>
      <th>Material</th>
      <th>Admission</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% userid= @user_id.id%>
    <% @instructor_enrollment = @enrollments.where('"enrollments"."instructor_id" = ?', "#{userid}") %>
    <% @instructor_enrollment.each do |enrollment| %>
        <tr>
          <td><%= enrollment.student_id %></td>
          <td><%= enrollment.instructor_id %></td>
          <td><%= enrollment.course_id %></td>
          <td><%= enrollment.grade %></td>
          <td><%= enrollment.material %></td>
          <td><%= enrollment.admission %></td>
          <td><%= link_to 'Show', enrollment %></td>
          <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
          <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Enrollment', new_enrollment_path %>
</div>

app/views/enrollments/index_student.html.erb
<div class="container row col-md-4 col-md-offset-4" style="left: 0%; top: 70px;">
  <p id="notice"><%= notice %></p>

  <h1>Listing Enrollments</h1>

  <table border="4">
    <thead>
    <tr>
      <th>Student id</th>
      <th>Instructor id</th>
      <th>Course id</th>
      <th>Grade</th>
      <th>Material</th>
      <th>Admission</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% userid= @user_id.id%>
    <% @student_enrollment = @enrollments.where('"enrollments"."student_id" = ?', "#{userid}") %>
    <% @student_enrollment.each do |enrollment| %>
        <tr>
          <td><%= enrollment.student_id %></td>
          <td><%= enrollment.instructor_id %></td>
          <td><%= enrollment.course_id %></td>
          <td><%= enrollment.grade %></td>
          <td><%= enrollment.material %></td>
          <td><%= enrollment.admission %></td>
          <td><%= link_to 'Show', enrollment %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Enrollment', new_enrollment_path %>
</div>

app/views/enrollments/new.html.erb
<div class="container row col-md-4 col-md-offset-4" style="left: 0%; top: 70px;">
<h1>New Enrollment</h1>

<%= render 'form' %>


  <% if can? :do_as_student, :all %>
      <%= link_to "Back", courses_path %>
  <% else %>
      <%= link_to 'Back', enrollments_path %>
  <% end %>
</div>

app/views/enrollments/show.html.erb
<div class="container row col-md-4 col-md-offset-4" style="left: 0%; top: 70px;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Student id:</strong>
  <%= @enrollment.student_id %>
</p>

<p>
  <strong>Instructor id:</strong>
  <%= @enrollment.instructor_id %>
</p>

<p>
  <strong>Course id:</strong>
  <%= @enrollment.course_id %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @enrollment.grade %>
</p>

<p>
  <strong>Material:</strong>
  <%= @enrollment.material %>
</p>

<p>
  <strong>Admission:</strong>
  <%= @enrollment.admission %>
</p>

  <%= link_to 'Edit', edit_enrollment_path(@enrollment) %>
  <% if can? :do_as_student, :all %>
      <%= link_to "Back", courses_path %>
  <% else %>
      <%= link_to 'Back', enrollments_path %>
  <% end %>
</div>