config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
#  get 'superadmins/index'
 # get 'superadmins/show'
 # get 'superadmins/new'

 # get 'superadmins/edit'
 # get 'admins/index'
#  get 'admins', to: 'admins#show'
 # get 'instructors/index'

 # get 'instructors/show'

 # get 'admins/index'

 # get 'admins', to: 'admins#show'

=======
>>>>>>> refs/remotes/origin/schen35

  #root to: 'users#index'
  root to: 'visitors#index'
  devise_for :users, :path =>'u'
  get '/superadmins/:id' => 'users#destroy'

  get 'index_instructor' => 'enrollments#index_instructor'
   get 'index_student' => 'enrollments#index_student'

  get '/enrollments', to: 'enrollments#new', as: 'student_enrollment'


  devise_scope :user do
<<<<<<< HEAD
    # get '/u/login', to: "devise/sessions#new", as: "login"
    # get '/u/logout', to: "devise/sessions#destroy", as: "logout"
    # get '/u/signout', to: "users/sessions#destroy", as: "signout"
    # get '/u/signup', to: "users#new", as: "signup"
=======
>>>>>>> refs/remotes/origin/schen35
    get '/u/sign_out' => 'devise/sessions#destroy'

  end


   resources :users
   resources :enrollments
   resources :courses
  resources :admins
  resources :superadmins
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  include Register
  # GET /courses
  # GET /courses.json
  def index
<<<<<<< HEAD
<<<<<<< HEAD
    @courses = Course.search(params[:search])
=======
    @courses = Course.all
    @user_id = session[:user_id]
    puts @user_id
>>>>>>> origin/devarenacn
=======

    @courses = Course.search(params[:search])
    @user_id = session[:user_id]
    puts @user_id

>>>>>>> refs/remotes/origin/schen35
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_path, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


<<<<<<< HEAD
    ActiveRecord::Base.connection.execute("INSERT INTO enrollments (student_id, course_id, instructor_id) VALUES (#{user.id}, #{course.id}, #{@get_instructor_id}) ")


<<<<<<< HEAD
=======

   # @users = User.all
   # @users.each do |find_user|
   #   relevant_courses = Courses.find(:all, :conditions => ["? = courses.Instructor",find_user.name ])
    #  relevant_courses.each do |find_instructor|
    #    users.enrollments << Enrollments.create(:course_id => course.id, :student_id => user.id, :instructor_id => find_instructor.id)
     # end
   # end
  end
=======
>>>>>>> refs/remotes/origin/schen35

>>>>>>> origin/devarenacn
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:Course_num, :Title, :Description, :Instructor, :Start_date, :End_date, :Status)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
  <div class="container row col-lg-12 col-md-12 col-sm-12" >
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        <fieldset>
  <div class="field">
    <%= f.label :Course_num %><br>
    <%= f.number_field :Course_num %>
  </div>
  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
    <!-- <%= f.text_area :Description, :value =>"something" %>-->
  </div>
          </fieldset>
        <fieldset>
  <div class="field">
    <%= f.label :Instructor %><br>
    <%= f.text_field :Instructor %>
  </div>
  <div class="field">
    <%= f.label :Start_date %><br>
    <%= f.date_select :Start_date %>
  </div>
  <div class="field">
    <%= f.label :End_date %><br>
    <%= f.date_select :End_date %>
  </div>
  <div class="field">
    <%= f.label :Status %>
    <%= f.check_box :Status %>
  </div>
          </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>



<% end %>
</div>

app/views/courses/edit.html.erb
  <div class="container">
    <div class="row col-md-8 col-md-offset-2" style="left: 0%; top: 70px;">
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>


  </div>
  </div>

app/views/courses/index.html.erb
  <div class="container row col-lg-12 col-md-12 col-sm-12 " style="left: 0%; top: 70px;">
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>
    <%= form_tag courses_path, :method => 'get' do %>
        <p>
        <%= text_field_tag :search, params[:search], placeholder: "Search Course" %>
        <%= submit_tag "Search", :name => nil %>
        </p>
    <% end %>
<<<<<<< HEAD
=======

>>>>>>> refs/remotes/origin/schen35

<<<<<<< HEAD
    <table>
=======
<table border="4">
<<<<<<< HEAD
>>>>>>> origin/devarenacn
=======

>>>>>>> refs/remotes/origin/schen35
  <thead>
    <tr>
      <th>Course num</th>
      <th>Title</th>
      <th>Description</th>
      <th>Instructor</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.Course_num %></td>
        <td><%= course.Title %></td>
        <td><%= course.Description %></td>
        <td><%= course.Instructor %></td>
        <td><%= course.Start_date %></td>
        <td><%= course.End_date %></td>
        <td><%= course.Status %></td>
        <% if can? :do_as_student, :all %>
<<<<<<< HEAD
            <% @course_id = course.id  %>
            <td><%= button_to "Enroll", new_enrollment_path(@course_id),  form_class: "Enroll", method: "get"  %></td>
<<<<<<< HEAD

=======
=======
            <td><%= link_to 'Check Detail', course %></td>
>>>>>>> refs/remotes/origin/schen35
        <% end %>
        <% if can? :do_as_instructor, :all %>
<<<<<<< HEAD
            <% @course_id = course  %>
            <td><%= button_to "Manage Enroll", edit_enrollment_path(@course_id),  form_class: "Enroll", method: "get"  %></td>
<<<<<<< HEAD
>>>>>>> origin/devarenacn
=======
=======
            <% @course_id = course.id  %>
>>>>>>> refs/remotes/origin/schen35
            <td><%= link_to 'Show', course %></td>
>>>>>>> refs/remotes/origin/schen35
        <% end %>
<<<<<<< HEAD
        <% if can? :do_as_instructor, :all %>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
<<<<<<< HEAD
=======
        <% end %>
        <% if can? :do_as_admin, :all %>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
            </tr>
<<<<<<< HEAD
=======

        <% if ((can? :do_as_instructor, :all)||(can? :do_as_admin, :all) )%>

        <% end %>
        <% if can? :do_as_admin, :all %>
            <td><%= link_to 'Edit', edit_course_path(course) %></td>
            <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
>>>>>>> refs/remotes/origin/schen35

=======
=======
<<<<<<< HEAD
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
            </tr>
=======
>>>>>>> origin/devarenacn
        <td><%= link_to 'Destroy', course, :method => :delete, :class=>:destroy, data: { confirm: 'Are you sure?' }%></td>
      </tr>
>>>>>>> 72fbd739d54b7853f8eb1948ea710fea944e13bb
>>>>>>> master
>>>>>>> origin/master
    <% end %>


  </tbody>
</table>

<br>
    <% if can? :do_as_admin, :all %>
    <%= link_to 'New Course', new_course_path %>
    <% end %>


  </div>

app/views/courses/new.html.erb
<div class="container">
  <div class="row col-md-4 col-md-offset-4" style="left: 0%; top: 70px;">
    <p id="notice"><%= notice %></p>
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>
</div>
  </div>

app/views/courses/search.html.erb
<% if @course.present? %>
  <%= render @course %>
<% else %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/courses/show.html.erb
<div class="container">
  <div class="row col-md-4 col-md-offset-4" style="left: 0%; top: 70px;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Course num:</strong>
  <%= @course.Course_num %>
</p>

<p>
  <strong>Title:</strong>
  <%= @course.Title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.Description %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @course.Instructor %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @course.Start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @course.End_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @course.Status %>
</p>
    <% if ((can? :do_as_admin, :all) || (can? :do_as_superadmin, :all))%>
<%= link_to 'Edit', edit_course_path(@course) %> |
    <% end %>
<%= link_to 'Back', courses_path %>

    <% if can? :do_as_student, :all %>
        <% session[:current_course]= @course.id %>
        |  <%= link_to 'Enroll', student_enrollment_path %>
    <% end %>
</div>
  </div>