config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
#  get 'superadmins/index'
 # get 'superadmins/show'
 # get 'superadmins/new'

 # get 'superadmins/edit'
 # get 'admins/index'
#  get 'admins', to: 'admins#show'
 # get 'instructors/index'

 # get 'instructors/show'

 # get 'admins/index'

 # get 'admins', to: 'admins#show'

=======
>>>>>>> refs/remotes/origin/schen35

  #root to: 'users#index'
  root to: 'visitors#index'
  devise_for :users, :path =>'u'
  get '/superadmins/:id' => 'users#destroy'

  get 'index_instructor' => 'enrollments#index_instructor'
   get 'index_student' => 'enrollments#index_student'

  get '/enrollments', to: 'enrollments#new', as: 'student_enrollment'


  devise_scope :user do
<<<<<<< HEAD
    # get '/u/login', to: "devise/sessions#new", as: "login"
    # get '/u/logout', to: "devise/sessions#destroy", as: "logout"
    # get '/u/signout', to: "users/sessions#destroy", as: "signout"
    # get '/u/signup', to: "users#new", as: "signup"
=======
>>>>>>> refs/remotes/origin/schen35
    get '/u/sign_out' => 'devise/sessions#destroy'

  end


   resources :users
   resources :enrollments
   resources :courses
  resources :admins
  resources :superadmins
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=> :delete %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
 <!-- <li><%= link_to 'Users', users_path %></li> -->
<% end %>
<% if user_signed_in? %>

    <% if can? :do_as_admin, :all %>

        <li><%#= link_to "Do as admin", admins_path %></li>
<<<<<<< HEAD

        <li><%= link_to "Manage admins & users", superadmins_path %></li>

=======
=======
<<<<<<< HEAD
        <li><%#= link_to "Do as admin", admins_path %></li>
=======
        <li><%= link_to "Do as admin", superadmins_path %></li>
>>>>>>> 72fbd739d54b7853f8eb1948ea710fea944e13bb
>>>>>>> master
>>>>>>> origin/master
    <% end %>
    <% if can? :do_as_instructor, :all %>
        <li><%= link_to "List course", courses_path %></li>
        <li><%= link_to "Check Enrollment", index_instructor_path %></li>
    <% end %>
    <% if can? :do_as_student, :all %>
        <li><%= link_to "Search course", courses_path %></li>
        <li><%= link_to "Check Enrollment", index_student_path %></li>
    <% end %>
    <% if can? :do_as_superadmin, :all %>
        <li><%= link_to "Manage admins & users", superadmins_path %></li>
        <li><%= link_to "Manage courses", courses_path %></li>
        <li><%= link_to "Manage enrollment", enrollments_path %></li>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse nav-justified navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if (can? :do_as_student, :all || !user_signed_in?) %>
          <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% end %>
      <% if ((can? :do_as_admin, :all) || (can? :do_as_superadmin, :all))%>
      <%= link_to 'Admin Home', root_path, class: 'navbar-brand' %>
      <% end %>
      <% if can? :do_as_instructor, :all %>
          <%= link_to 'Instructor Home', root_path, class: 'navbar-brand' %>
      <% end %>

      </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

      <!-- Style -->
    <link href="https://cdn.ncsu.edu/brand-assets/bootstrap/css/bootstrap.css" rel="stylesheet" media="screen" type="text/css" />
    <!-- /.Style -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Class Protal" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Class Protal" %>">
    <%= stylesheet_link_tag 'default', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>